<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RcBwZO9Service extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rcBwZO9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rcBwZO9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'RecommendProduct' => ['privates', '.errored..service_locator.rcBwZO9.Plugin\\Recommend42\\Entity\\RecommendProduct', NULL, 'Cannot autowire service ".service_locator.rcBwZO9": it references class "Plugin\\Recommend42\\Entity\\RecommendProduct" but no such service exists.'],
        ], [
            'RecommendProduct' => 'Plugin\\Recommend42\\Entity\\RecommendProduct',
        ]);
    }
}
