<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProductSubscriberService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\EventSubscriber\AdminProductSubscriber' shared autowired service.
     *
     * @return \Plugin\Rental\EventSubscriber\AdminProductSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/EventSubscriber/AdminProductSubscriber.php';

        return $container->privates['Plugin\\Rental\\EventSubscriber\\AdminProductSubscriber'] = new \Plugin\Rental\EventSubscriber\AdminProductSubscriber(($container->privates['Plugin\\Rental\\Repository\\RentalProductRepository'] ?? $container->load('getRentalProductRepositoryService')));
    }
}
