<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselFeatureTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\CarouselFeature\Form\Type\CarouselFeatureType' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Form\Type\CarouselFeatureType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Form/Type/CarouselFeatureType.php';

        return $container->privates['Plugin\\CarouselFeature\\Form\\Type\\CarouselFeatureType'] = new \Plugin\CarouselFeature\Form\Type\CarouselFeatureType();
    }
}
