<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselServiceService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\CarouselFeature\Service\CarouselService' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Service\CarouselService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Service/CarouselService.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Service/ImageService.php';

        return $container->privates['Plugin\\CarouselFeature\\Service\\CarouselService'] = new \Plugin\CarouselFeature\Service\CarouselService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['Plugin\\CarouselFeature\\Service\\ImageService'] ?? ($container->privates['Plugin\\CarouselFeature\\Service\\ImageService'] = new \Plugin\CarouselFeature\Service\ImageService(($container->services['kernel'] ?? $container->get('kernel', 1))))));
    }
}
