<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigServiceService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\CarouselFeature\Service\ConfigService' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Service\ConfigService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Service/ConfigService.php';

        return $container->privates['Plugin\\CarouselFeature\\Service\\ConfigService'] = new \Plugin\CarouselFeature\Service\ConfigService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
