<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselFeatureRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\CarouselFeature\Repository\CarouselFeatureRepository' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Repository\CarouselFeatureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Repository/CarouselFeatureRepository.php';

        return $container->privates['Plugin\\CarouselFeature\\Repository\\CarouselFeatureRepository'] = new \Plugin\CarouselFeature\Repository\CarouselFeatureRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
