<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigController3Service extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\MakerProductBlock\Controller\Admin\ConfigController' shared autowired service.
     *
     * @return \Plugin\MakerProductBlock\Controller\Admin\ConfigController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/MakerProductBlock/Controller/Admin/ConfigController.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());
        $b = ($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService'));
        $c = ($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container)));

        $container->services['Plugin\\MakerProductBlock\\Controller\\Admin\\ConfigController'] = $instance = new \Plugin\MakerProductBlock\Controller\Admin\ConfigController(($container->services['Plugin\\MakerProductBlock\\Repository\\MakerBlockRepository'] ?? $container->load('getMakerBlockRepositoryService')), ($container->services['Plugin\\MakerProductBlock\\Service\\MakerService'] ?? $container->load('getMakerServiceService')), $a, ($container->privates['Eccube\\Repository\\BlockRepository'] ?? $container->getBlockRepositoryService()), ($container->privates['Eccube\\Repository\\Master\\DeviceTypeRepository'] ?? $container->getDeviceTypeRepositoryService()), $b, ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), $c);

        $instance->setEccubeConfig($c);
        $instance->setEntityManager($a);
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setSession(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()));
        $instance->setFormFactory($b);
        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Plugin\\MakerProductBlock\\Controller\\Admin\\ConfigController', $container));

        return $instance;
    }
}
