<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Maker42\Form\Type\MakerType' shared autowired service.
     *
     * @return \Plugin\Maker42\Form\Type\MakerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Maker42/Form/Type/MakerType.php';

        return $container->privates['Plugin\\Maker42\\Form\\Type\\MakerType'] = new \Plugin\Maker42\Form\Type\MakerType(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
    }
}
