<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerProductBlockEventService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\MakerProductBlock\MakerProductBlockEvent' shared autowired service.
     *
     * @return \Plugin\MakerProductBlock\MakerProductBlockEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/MakerProductBlock/MakerProductBlockEvent.php';

        return $container->privates['Plugin\\MakerProductBlock\\MakerProductBlockEvent'] = new \Plugin\MakerProductBlock\MakerProductBlockEvent(($container->services['Plugin\\MakerProductBlock\\Service\\MakerService'] ?? $container->load('getMakerServiceService')));
    }
}
