<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerServiceService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\MakerProductBlock\Service\MakerService' shared autowired service.
     *
     * @return \Plugin\MakerProductBlock\Service\MakerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/MakerProductBlock/Service/MakerService.php';

        return $container->services['Plugin\\MakerProductBlock\\Service\\MakerService'] = new \Plugin\MakerProductBlock\Service\MakerService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['Eccube\\Repository\\ProductRepository'] ?? $container->getProductRepositoryService()));
    }
}
