<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailServiceService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\Service\MailService' shared autowired service.
     *
     * @return \Eccube\Service\MailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/MailService.php';

        return $container->privates['Eccube\\Service\\MailService'] = new \Eccube\Service\MailService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['Eccube\\Repository\\MailTemplateRepository'] ?? $container->load('getMailTemplateRepositoryService')), ($container->privates['Eccube\\Repository\\MailHistoryRepository'] ?? $container->load('getMailHistoryRepositoryService')), ($container->privates['Eccube\\Repository\\BaseInfoRepository'] ?? $container->getBaseInfoRepositoryService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))), $container);
    }
}
