<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerBlockRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\MakerProductBlock\Repository\MakerBlockRepository' shared autowired service.
     *
     * @return \Plugin\MakerProductBlock\Repository\MakerBlockRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/MakerProductBlock/Repository/MakerBlockRepository.php';

        return $container->services['Plugin\\MakerProductBlock\\Repository\\MakerBlockRepository'] = new \Plugin\MakerProductBlock\Repository\MakerBlockRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
