<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Maker42\Repository\MakerRepository' shared autowired service.
     *
     * @return \Plugin\Maker42\Repository\MakerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/Maker42/Repository/MakerRepository.php';

        return $container->privates['Plugin\\Maker42\\Repository\\MakerRepository'] = new \Plugin\Maker42\Repository\MakerRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
