<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductTypeExtension2Service extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\Form\Extension\Admin\ProductTypeExtension' shared autowired service.
     *
     * @return \Plugin\Rental\Form\Extension\Admin\ProductTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Form/Extension/Admin/ProductTypeExtension.php';

        return $container->privates['Plugin\\Rental\\Form\\Extension\\Admin\\ProductTypeExtension'] = new \Plugin\Rental\Form\Extension\Admin\ProductTypeExtension(($container->privates['Plugin\\Rental\\Repository\\RentalProductRepository'] ?? $container->load('getRentalProductRepositoryService')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
