<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalFrontTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\Form\Type\RentalFrontType' shared autowired service.
     *
     * @return \Plugin\Rental\Form\Type\RentalFrontType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Form/Type/RentalFrontType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Service/RentalCalculationService.php';

        return $container->privates['Plugin\\Rental\\Form\\Type\\RentalFrontType'] = new \Plugin\Rental\Form\Type\RentalFrontType(($container->privates['Plugin\\Rental\\Service\\RentalCalculationService'] ?? ($container->privates['Plugin\\Rental\\Service\\RentalCalculationService'] = new \Plugin\Rental\Service\RentalCalculationService())));
    }
}
