<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendProductTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Recommend42\Form\Type\RecommendProductType' shared autowired service.
     *
     * @return \Plugin\Recommend42\Form\Type\RecommendProductType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Recommend42/Form/Type/RecommendProductType.php';

        return $container->privates['Plugin\\Recommend42\\Form\\Type\\RecommendProductType'] = new \Plugin\Recommend42\Form\Type\RecommendProductType(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
