<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalOrderListenerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\EventListener\RentalOrderListener' shared autowired service.
     *
     * @return \Plugin\Rental\EventListener\RentalOrderListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/EventListener/RentalOrderListener.php';

        return $container->privates['Plugin\\Rental\\EventListener\\RentalOrderListener'] = new \Plugin\Rental\EventListener\RentalOrderListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['Plugin\\Rental\\Repository\\RentalProductRepository'] ?? $container->load('getRentalProductRepositoryService')));
    }
}
