<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalOrderRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\Repository\RentalOrderRepository' shared autowired service.
     *
     * @return \Plugin\Rental\Repository\RentalOrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Repository/RentalOrderRepository.php';

        return $container->privates['Plugin\\Rental\\Repository\\RentalOrderRepository'] = new \Plugin\Rental\Repository\RentalOrderRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
