<?php

namespace ContainerAlJK2dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalControllerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\Rental\Controller\Admin\RentalController' shared autowired service.
     *
     * @return \Plugin\Rental\Controller\Admin\RentalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Controller/Admin/RentalController.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Service/RentalService.php';

        $a = ($container->privates['Plugin\\Rental\\Repository\\RentalOrderRepository'] ?? $container->load('getRentalOrderRepositoryService'));
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['Plugin\\Rental\\Controller\\Admin\\RentalController'] = $instance = new \Plugin\Rental\Controller\Admin\RentalController($a, new \Plugin\Rental\Service\RentalService($b, ($container->privates['Plugin\\Rental\\Repository\\RentalProductRepository'] ?? $container->load('getRentalProductRepositoryService')), $a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))));

        $instance->setEccubeConfig(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
        $instance->setEntityManager($b);
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setSession(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()));
        $instance->setFormFactory(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')));
        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Plugin\\Rental\\Controller\\Admin\\RentalController', $container));

        return $instance;
    }
}
