<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PLuO45SService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pLuO45S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pLuO45S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carousel' => ['privates', '.errored..service_locator.pLuO45S.Plugin\\CarouselFeature\\Entity\\CarouselFeature', NULL, 'Cannot autowire service ".service_locator.pLuO45S": it references class "Plugin\\CarouselFeature\\Entity\\CarouselFeature" but no such service exists.'],
        ], [
            'carousel' => 'Plugin\\CarouselFeature\\Entity\\CarouselFeature',
        ]);
    }
}
