<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T8r3XrKService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t8r3XrK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t8r3XrK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Maker' => ['privates', '.errored..service_locator.t8r3XrK.Plugin\\Maker42\\Entity\\Maker', NULL, 'Cannot autowire service ".service_locator.t8r3XrK": it references class "Plugin\\Maker42\\Entity\\Maker" but no such service exists.'],
        ], [
            'Maker' => 'Plugin\\Maker42\\Entity\\Maker',
        ]);
    }
}
