<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorityVoterService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.voter.Eccube\Security\Voter\AuthorityVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Security/Voter/AuthorityVoter.php';

        return $container->privates['debug.security.voter.Eccube\\Security\\Voter\\AuthorityVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Eccube\Security\Voter\AuthorityVoter(($container->privates['Eccube\\Repository\\AuthorityRoleRepository'] ?? $container->getAuthorityRoleRepositoryService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container)))), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
