<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselConfigRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\CarouselFeature\Repository\CarouselConfigRepository' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Repository\CarouselConfigRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Repository/CarouselConfigRepository.php';

        return $container->privates['Plugin\\CarouselFeature\\Repository\\CarouselConfigRepository'] = new \Plugin\CarouselFeature\Repository\CarouselConfigRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
