<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselListControllerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\CarouselFeature\Controller\Admin\CarouselListController' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Controller\Admin\CarouselListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Controller/Admin/CarouselListController.php';

        $container->services['Plugin\\CarouselFeature\\Controller\\Admin\\CarouselListController'] = $instance = new \Plugin\CarouselFeature\Controller\Admin\CarouselListController(($container->privates['Plugin\\CarouselFeature\\Service\\CarouselService'] ?? $container->load('getCarouselServiceService')));

        $instance->setEccubeConfig(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
        $instance->setEntityManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setSession(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()));
        $instance->setFormFactory(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')));
        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setContainer(($container->privates['.service_locator.EGyensF'] ?? $container->load('get_ServiceLocator_EGyensFService'))->withContext('Plugin\\CarouselFeature\\Controller\\Admin\\CarouselListController', $container));

        return $instance;
    }
}
