<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselListTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\CarouselFeature\Form\Type\CarouselListType' shared autowired service.
     *
     * @return \Plugin\CarouselFeature\Form\Type\CarouselListType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/CarouselFeature/Form/Type/CarouselListType.php';

        return $container->privates['Plugin\\CarouselFeature\\Form\\Type\\CarouselListType'] = new \Plugin\CarouselFeature\Form\Type\CarouselListType();
    }
}
