<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigController2Service extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\CategoryProductBlock\Controller\Admin\ConfigController' shared autowired service.
     *
     * @return \Plugin\CategoryProductBlock\Controller\Admin\ConfigController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/CategoryProductBlock/Controller/Admin/ConfigController.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['Plugin\\CategoryProductBlock\\Controller\\Admin\\ConfigController'] = $instance = new \Plugin\CategoryProductBlock\Controller\Admin\ConfigController($a, ($container->privates['Plugin\\CategoryProductBlock\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()));

        $instance->setEccubeConfig(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
        $instance->setEntityManager($a);
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setSession(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()));
        $instance->setFormFactory(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')));
        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Plugin\\CategoryProductBlock\\Controller\\Admin\\ConfigController', $container));

        return $instance;
    }
}
