<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselFeatureService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pLuO45S.Plugin\CarouselFeature\Entity\CarouselFeature' shared service.
     *
     * @return \Plugin\CarouselFeature\Entity\CarouselFeature
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pLuO45S": it references class "Plugin\\CarouselFeature\\Entity\\CarouselFeature" but no such service exists.');
    }
}
