<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeftTextBlockTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\LeftTextBlock\Form\Type\Admin\LeftTextBlockType' shared autowired service.
     *
     * @return \Plugin\LeftTextBlock\Form\Type\Admin\LeftTextBlockType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/LeftTextBlock/Form/Type/Admin/LeftTextBlockType.php';

        return $container->privates['Plugin\\LeftTextBlock\\Form\\Type\\Admin\\LeftTextBlockType'] = new \Plugin\LeftTextBlock\Form\Type\Admin\LeftTextBlockType();
    }
}
