<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t8r3XrK.Plugin\Maker42\Entity\Maker' shared service.
     *
     * @return \Plugin\Maker42\Entity\Maker
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.t8r3XrK": it references class "Plugin\\Maker42\\Entity\\Maker" but no such service exists.');
    }
}
