<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakerControllerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\Maker42\Controller\MakerController' shared autowired service.
     *
     * @return \Plugin\Maker42\Controller\MakerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Maker42/Controller/MakerController.php';

        $container->services['Plugin\\Maker42\\Controller\\MakerController'] = $instance = new \Plugin\Maker42\Controller\MakerController(($container->privates['Plugin\\Maker42\\Repository\\MakerRepository'] ?? $container->load('getMakerRepositoryService')));

        $instance->setEccubeConfig(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
        $instance->setEntityManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setSession(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()));
        $instance->setFormFactory(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')));
        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setContainer(($container->privates['.service_locator.EGyensF'] ?? $container->load('get_ServiceLocator_EGyensFService'))->withContext('Plugin\\Maker42\\Controller\\MakerController', $container));

        return $instance;
    }
}
