<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsControllerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Customize\Controller\NewsController' shared autowired service.
     *
     * @return \Customize\Controller\NewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/app/Customize/Controller/NewsController.php';

        $container->services['Customize\\Controller\\NewsController'] = $instance = new \Customize\Controller\NewsController();

        $instance->setContainer(($container->privates['.service_locator.EGyensF'] ?? $container->load('get_ServiceLocator_EGyensFService'))->withContext('Customize\\Controller\\NewsController', $container));

        return $instance;
    }
}
