<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Plugin\Rental\Nav' shared autowired service.
     *
     * @return \Plugin\Rental\Nav
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Common/EccubeNav.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Nav.php';

        return $container->services['Plugin\\Rental\\Nav'] = new \Plugin\Rental\Nav(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
    }
}
