<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductDetailListenerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\EventListener\ProductDetailListener' shared autowired service.
     *
     * @return \Plugin\Rental\EventListener\ProductDetailListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/EventListener/ProductDetailListener.php';

        return $container->privates['Plugin\\Rental\\EventListener\\ProductDetailListener'] = new \Plugin\Rental\EventListener\ProductDetailListener(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')), ($container->privates['Plugin\\Rental\\Repository\\RentalProductRepository'] ?? $container->load('getRentalProductRepositoryService')));
    }
}
