<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductTypeExtensionService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Maker42\Form\Extension\ProductTypeExtension' shared autowired service.
     *
     * @return \Plugin\Maker42\Form\Extension\ProductTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Maker42/Form/Extension/ProductTypeExtension.php';

        return $container->privates['Plugin\\Maker42\\Form\\Extension\\ProductTypeExtension'] = new \Plugin\Maker42\Form\Extension\ProductTypeExtension(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))), ($container->privates['Plugin\\Maker42\\Repository\\MakerRepository'] ?? $container->load('getMakerRepositoryService')));
    }
}
