<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalConfigTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\Form\Type\RentalConfigType' shared autowired service.
     *
     * @return \Plugin\Rental\Form\Type\RentalConfigType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Form/Type/RentalConfigType.php';

        return $container->privates['Plugin\\Rental\\Form\\Type\\RentalConfigType'] = new \Plugin\Rental\Form\Type\RentalConfigType();
    }
}
