<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalProductRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\Rental\Repository\RentalProductRepository' shared autowired service.
     *
     * @return \Plugin\Rental\Repository\RentalProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/app/Plugin/Rental/Repository/RentalProductRepository.php';

        return $container->privates['Plugin\\Rental\\Repository\\RentalProductRepository'] = new \Plugin\Rental\Repository\RentalProductRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
