<?php

namespace Container1V1QCkx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchConfigTypeService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Plugin\MakerProductBlock\Form\Type\Admin\SearchConfigType' shared autowired service.
     *
     * @return \Plugin\MakerProductBlock\Form\Type\Admin\SearchConfigType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/app/Plugin/MakerProductBlock/Form/Type/Admin/SearchConfigType.php';

        return $container->privates['Plugin\\MakerProductBlock\\Form\\Type\\Admin\\SearchConfigType'] = new \Plugin\MakerProductBlock\Form\Type\Admin\SearchConfigType();
    }
}
