<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1V1QCkx\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1V1QCkx/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1V1QCkx.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1V1QCkx\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \Container1V1QCkx\Eccube_KernelDevDebugContainer([
    'container.build_hash' => '1V1QCkx',
    'container.build_id' => '9336e0e8',
    'container.build_time' => 1751359190,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1V1QCkx');
